{{- if eq .Values.global.network "ephemery" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "geth-lighthouse.serviceAccountName" . }}
  labels:
    {{- include "geth-lighthouse.labels" . | nindent 4 }}
rules:
    - apiGroups: ["apps", "extensions"]
      resources: ["statefulsets"]
      resourceNames: 
      - "{{ include "geth-lighthouse.fullname" . }}"
      verbs: ["get", "patch", "list", "watch"]
{{- end }}
