{{- if eq .Values.global.network "ephemery" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "geth-lighthouse.serviceAccountName" . }}
  labels:
    {{- include "geth-lighthouse.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "geth-lighthouse.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "geth-lighthouse.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
