apiVersion: v1
kind: Service
metadata:
  name: {{ include "geth-lighthouse.fullname" . }}-p2p
  labels:
    {{- include "geth-lighthouse.labels" $ | nindent 4 }}
    pod: {{ include "geth-lighthouse.fullname" $ }}-0
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    - port: {{ .Values.geth.ports.p2p}}
      targetPort: geth-p2p-udp
      nodePort: {{ .Values.geth.ports.p2p}}
      protocol: UDP
      name: geth-p2p-udp
    - port: {{ .Values.geth.ports.p2p}}
      targetPort: geth-p2p-tcp
      nodePort: {{ .Values.geth.ports.p2p}}
      protocol: TCP
      name: geth-p2p-tcp
    - port: {{ .Values.lighthouse.ports.p2p}}
      targetPort: lh-p2p-udp
      nodePort: {{ .Values.lighthouse.ports.p2p}}
      protocol: UDP
      name: lh-p2p-udp
    - port: {{ .Values.lighthouse.ports.p2p}}
      targetPort: lh-p2p-tcp
      nodePort: {{ .Values.lighthouse.ports.p2p}}
      protocol: TCP
      name: lh-p2p-tcp
  selector:
    {{- include "geth-lighthouse.selectorLabels" . | nindent 4 }}
    statefulset.kubernetes.io/pod-name: "{{ include "geth-lighthouse.fullname" $ }}-0"