{{- if eq .Values.global.network "ephemery" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "lighthouse-vc.serviceAccountName" . }}-ephemery
  labels:
    {{- include "lighthouse-vc.labels" . | nindent 4 }}
rules:
    - apiGroups: ["apps", "extensions"]
      resources: ["statefulsets"]
      resourceNames: 
      - "{{ include "lighthouse-vc.fullname" . }}"
      verbs: ["get", "patch", "list", "watch"]
{{- end }}
