{{- if eq .Values.global.network "ephemery" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "lighthouse-vc.serviceAccountName" . }}-ephemery
  labels:
    {{- include "lighthouse-vc.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "lighthouse-vc.serviceAccountName" . }}-ephemery
subjects:
  - kind: ServiceAccount
    name: {{ include "lighthouse-vc.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}

