{{- range $i, $e := until (int $.Values.global.replicas) }}
{{- $rangeItem := . -}}
{{- with $ }}
{{- $port := add $.Values.lighthouse.ports.nodePortsStartAt $i }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lighthouse-vc.fullname" . }}-nodeport-{{ $i }}
  labels:
    {{- include "lighthouse-vc.labels" $ | nindent 4 }}
    pod: {{ include "lighthouse-vc.fullname" $ }}-{{ $i }}
    type: lh-vc-http
spec:
  type: NodePort
  externalTrafficPolicy: Cluster
  ports:
    - port: {{ .Values.lighthouse.ports.httpJson}}
      targetPort: lh-vc-http
      nodePort: {{ $port }}
      protocol: TCP
      name: lh-vc-http
  selector:
    {{- include "lighthouse-vc.selectorLabels" . | nindent 4 }}
    statefulset.kubernetes.io/pod-name: {{ include "lighthouse-vc.fullname" $ }}-{{ $i }}
  
{{- end }}
{{- end }}