apiVersion: v1
kind: Service
metadata:
  name: {{ include "lighthouse-vc.fullname" . }}
  labels:
    {{- include "lighthouse-vc.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.lighthouse.ports.httpJson }}
      targetPort: {{ .Values.lighthouse.ports.httpJson }}
      protocol: TCP
      name: lh-vc-http-json
    - port: {{ .Values.lighthouse.ports.metrics }}
      targetPort: {{ .Values.lighthouse.ports.metrics }}
      protocol: TCP
      name: lh-vc-metrics
  selector:
    {{- include "lighthouse-vc.selectorLabels" . | nindent 4 }}
